name: nginx-server
version: 1.23.4
summary: nginx server
description: nginx server

base: core22
confinement: devmode
grade: stable

architectures:
  - build-on: amd64
  - build-on: arm64
  - build-on: armhf

apps:
  nginx-server:
    command: sbin/nginx -p $SNAP_DATA
    daemon: simple
    plugs:
      - network
      - network-bind

parts:
  nginx:
    plugin: autotools
    source: https://nginx.org/download/nginx-1.23.4.tar.gz
    autotools-configure-parameters: 
      - --prefix=''
    build-packages:
      - libpcre3-dev
      - zlib1g-dev
    stage-packages:
      - libpcre3
      - zlib1g
